### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by migueldvb** [lsst/afw#51]
There's 21 test failures that appear to be related with cfitsio errors because some files cannot be found by git-lfs. I have put the full log at:
http://sprunge.us/NEPR

**Comment by jdswinbank** [comment]
Can you expand a bit on exactly what's going wrong here? You'll certainly see failures if you try to run the `afw` tests without `afwdata` being properly available -- but they won't run automatically without `afwdata` being set up. Did you manually clone and enable `afwdata`? Are you using some build tool like `lsstsw` or `eups distrib`? Do you have `git lfs` set up on your system?

For what it's worth, I've just cloned the latest `afwdata` (including the `lfs` files) on my system and run the `afw` test suite. There's no data missing, and all the tests pass, when things are properly set up.

**Comment by migueldvb** [comment]
I have found this error when I tried to build the stack using `lsst-build`. Igit lfs installed and other dependencies needed to install from source are available on my system. Probably afwdata was not set up earlier because it is listed as an optional dependency to afw. I guess this may be a bug in lsst-build because it breaks the installation of the stack.

**Comment by wmwv** [comment]
@migueldvb Could you provide a clear test case that recreates your error?

I wasn't able to clearly reconstruct the sequence of commands run from the log.

Unfortunately git-lfs is still causing a bit of trouble and we're trying to pursue and identify all of the different failure modes.  My speculation is that `afwdata` was cloned successfully, but that the git-lfs files were not successfully downloaded.  `afwdata` was then successfully set up, but the data weren't actually there.

**Comment by migueldvb** [comment]
I have used these commands to build the stack using `lsst-build`
```
export REPOSITORY_PATTERN="git@github.com:lsst/%(product)s.git|https://github.com/lsst/%(product)s.git/"
$ ./bin/lsst-build prepare --exclusion-map=exclusions.txt lsst_distrib/ ip_diffim
$ ./bin/lsst-build build lsst_distrib
```
where the contents of the exclusions.txt file are:
```
# Exclusion map. Format:
# dependency regex      product regex

cuda_toolkit            .*
cuda_sdk                .*
scipy                   .*
healpy                  .*
condor                  .*
```
I cannot reproduce the test failures now so it is likely that they were caused by a problem with my git-lfs installation.

**Comment by jdswinbank** [comment]
If this isn't reproducible, it sounds like a temporary glitch. I'm closing down the issue, but do please reopen if it continues to be a problem.
